name: C/C++ CI

on:
  push:
    branches: master
    paths:
    - .github/workflows/c-cpp.yml
    - Makefile
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/c-cpp.yml
    - Makefile
    - '**.[ch]'

permissions: {}

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: make
    - name: Test
      run: make check
  
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: make
    - name: Test
      run: make check
  
  openbsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap OpenBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xget.git
    - name: Build
      run: make
    - name: Test
      run: make check

  freebsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap FreeBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: freebsd-latest
    - name: Install dependencies
      run: pkg install -y pkgconf openssl
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xget.git
    - name: Build
      run: make
    - name: Test
      run: make check