name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/c-cpp.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbsd-dev
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: |
        CFLAGS=$(pkg-config --cflags libbsd-overlay) ./configure LDFLAGS=$(pkg-config --libs libbsd-overlay)
        make
  
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: ./configure && make
  
  openbsd:
    runs-on: macos-10.15
    steps:
    - name: Bootstrap OpenBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xdccget.git
    - name: build
      run: ./configure && make

  freebsd:
    runs-on: macos-10.15
    steps:
    - name: Bootstrap FreeBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: freebsd-latest
    - name: Install dependencies
      run: pkg install -y pkgconf openssl meson
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xdccget.git
    - name: build
      run: ./configure && make
