name: Clang Analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -qq libbsd-dev clang-tidy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run clang-tidy
      run: >
        clang-tidy
        --checks 'clang-analyzer-*'
        xdccget.c
        --
        -D_FILE_OFFSET_BITS=64
        $(pkg-config --cflags libbsd-overlay)
