name: Infer

on:
  push:
    branches: master
    paths:
    - .github/workflows/infer.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/infer.yml
    - meson.build
    - '**.[ch]'
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install meson infer

      - name: Build xdccget
        run: |
          meson setup build
          ninja -C build

      - name: Run Infer
        run: infer --sarif --compilation-database build/compile_commands.json

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: infer-out/report.sarif
