name: Infer

on:
  push:
    branches: master
    paths:
    - .github/workflows/infer.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/infer.yml
    - meson.build
    - '**.[ch]'
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  build-infer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: facebook/infer

      - name: Install opam
        run: sudo apt install opam

      - name: Build infer
        run: |
          ./build-infer.sh --yes clang
          make
          ls
          
  run-infer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install meson
        run: sudo apt install meson

      - name: Build xget
        run: |
          meson setup build
          ninja -C build

      - name: Run infer
        run: infer --compilation-database build/compile_commands.json --output-sarif ../results
        
      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v2
